image: python:3.12

stages:
  - build
  - deploy

variables:
  DEPLOY_DIR: /var/www/arch-docs/
  SSH_USER: root

build-site:
  stage: build
  script:
    - pip install -r requirements.txt
    - mkdocs build
  artifacts:
    paths:
      - site/

deploy-site:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y rsync openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_IP >> ~/.ssh/known_hosts
    - rsync -avz --delete site/ $SSH_USER@$DEPLOY_IP:$DEPLOY_DIR
