site_name: Arch Docs
site_url: https://soupup.online

repo_url: https://github.com/SouPuppy/Arch
repo_name: SouPuppy/Arch

theme:
  name: material
  # navigation settings
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

markdown_extensions:
  # enable math rendering with KaTeX
  - pymdownx.arithmatex:
      generic: true
  # syntax highlighting on code blocks and inline code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # grids for tables
  - attr_list
  - md_in_html
  # enable emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css